### ISSUE TITLE
issue with plugin resetting config

### ISSUE THREAD

**Issue by xstar97** [Steve-Tech/DynamicDNS-Spigot#5]
https://github.com/Steve-Tech/DynamicDNS-Spigot/blob/b284209595c9794bb6b79cb1d1ca57f406950ae1/src/main/java/me/stevetech/dynamicdns/DynamicDNS.java#L54

the line above is constantly resetting the config.

**Comment by Steve-Tech** [comment]
I'll be able to have a better look near the end of next week, but I've never had an issue with that line resetting a valid config.

Maybe try wrapping some of your config's strings in quotes in case they're getting misinterpreted as yaml, causing the config to be invalid so it resets it.

Also could you provide some info on the DDNS service your using and the server, like Minecraft version, Spigot/Paper/other, etc.

**Comment by Steve-Tech** [comment]
I just realised, if you copied the config off the README, then the `@` in the namecheap section would break things, wrapping it in quotes fixes that (`'@'`), and I've corrected the README.

**Comment by xstar97** [comment]
i remove the others and only used cloudflare portion. still the same issue.

**Comment by Wetzel402** [comment]
I can confirm I have the same problem.  I've tried both...

```
# The Configuration File for Steve's DynamicDNS Plugin  
period: 3600 # The period between updating IPs in seconds (3600 = 1 hour)

duckdns:
  enabled: true
  domain: mc.xxxxx.duckdns.org # Your subdomain on DuckDNS.org
  token: xxxxxxxxxx # Your token on DuckDNS.org
```
```
# The Configuration File for Steve's DynamicDNS Plugin  
period: 3600 # The period between updating IPs in seconds (3600 = 1 hour)

afraid:
  enabled: false
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # The token taken from the URL on the Dynamic DNS page (eg. http://freedns.afraid.org/dynamic/update.php?xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)

duckdns:
  enabled: true
  domain: mc.xxxxxxxx.duckdns.org # Your subdomain on DuckDNS.org
  token: xxxxxxxxxxx # Your token on DuckDNS.org

dynu:
  enabled: false
  hostname: example.ddnsfree.com # Your domain on Dynu
  password: password as plaintext, md5 or sha256 # Your password for Dynu (preferably hashed as md5 or sha256 so you're not storing your password in this file)

noip:
  enabled: false
  hostname: example.ddnsfree.com # Your domain on No-IP
  username: username # The username to your account
  password: password # The password to your account (sadly they don't support hashed passwords)

namecheap:
  enabled: false
  subdomain: '@' # subdomain of server, use '@' if none, multiple subdomains can be updated if separated by a comma ',' e.g. mc,map
  domain: exampledomain.com
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # The token under the "Advanced DNS" Section in your namecheap domain list

cloudflare:
  enabled: false
  name: example.com # The dns record name to get the record ID for
  zone_id: 023e105f4ecef8ad9ca31a8372d0c353 # The Zone ID from the Cloudflare Dash
  token: 21f72dee0e91a40be0a5964f6695fa8c # The API Token generated from the Cloudflare Dash, needs DNS Edit permissions

custom:
  enabled: false
  url: https://example.com/?ip=%ip% # The URL to your custom DDNS service, %ip% will be replaced with an ip given as an argument to /updateip [IP]
```

In either case the default was added to the top of the config and causes an error...

```
domain: exampledomain
token: a7c4d0ad-114e-40ef-ba1d-d217904a50f2
```
`[14:59:09 WARN]: [DuckDNS] Configuration Error: Check your Token and Domain are correct in the config.`

**Comment by Wetzel402** [comment]
I just realized the 1.0 release if labeled as `latest`.  The 2.0 release which is the most recent does not have this bug.  I was able to setup the config as expected and didn't receive any errors.  I'm not able to connect to my MC server still but that is likely a different issue right now.

**Comment by Wetzel402** [comment]
To clarify, should I be able to simply set this up and access my server in game via the duckdns domain and default port?  My MC server is running in docker with many other services including a NGINX instance.  I'm not sure if any of that is causing problems.
